// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function name(param) {
  return param[/* name */0];
}

var x = /* B */Block.__(0, [1]);

var y = /* C */Block.__(1, [/* record */[/* name */"A"]]);

exports.name = name;
exports.x    = x;
exports.y    = y;
/* No side effect */
